export interface ProductType {
  id: number,
  type: string,
  category: {
    name: string,
    tag: string,
  },
  name: string,
  favorite: boolean,
  price: number,
  originalPrice?: number,
  image?: string,
  onSale?: boolean,
  quantity?: number,
  color?: string,
  thumbnail?: string[],
  model?: {
    photo: string,
    name: string,
    height: string,
    bust: string,
    waist: string,
    hips: string,
    dress: number,
  },
}

export const  Products: ProductType[] = [
  {
    id: 67,
    type: 'nicole-thong',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Nicole Thong',
    favorite: false,
    price: 95.00,
    image: '/assets/images/Nicole_Bra_ThongChains_Back.webp',
    onSale: false,
    color: 'midnight',
    thumbnail: [
      "/assets/images/Nicole_Bra_ThongChains_Back.webp",
      "/assets/images/Nicole_ThongChains_Front1.webp",
      "/assets/images/Nicole_ThongChains_Back1.webp",
      "/assets/images/Nicole_ThongChains_Side.webp",
      "/assets/images/Nicole_Thong_Suspender_Front.webp",
      "/assets/images/Nicole_ThongChains_SuspenderChains_Back.webp",
      "/assets/images/Nicole_ThongChains_SuspenderChains_Side.webp",
      "/assets/images/Nicole_Bra_ThongChains_Front.webp",
      "/assets/images/Nicole_Bra_ThongChains_Side.webp",
      "/assets/images/Nicole2.jpg",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Thong_Front_d.jpg",
      name: "Sianie",
      height: '5\' 9\'\' / 175 CM',
      bust: '33.5" / 10D',
      waist: '26" / 66cm',
      hips: '36.5" / 93cm',
      dress: 6,
    }
  },
  {
    id: 68,
    type: 'nicole-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Nicole Bra',
    favorite: false,
    price: 120.00,
    image: '/assets/images/Nicole_Bra_ThongChains_Front.webp',
    onSale: false,
    color: 'midnight',
    thumbnail: [
      "/assets/images/Nicole_Bra_ThongChains_Front.webp",
      "/assets/images/Nicole_Bra_Front2.jpg",
      "/assets/images/Nicole_Bra_Back1.jpg",
      "/assets/images/Nicole_Bra_Side.jpg",
      "/assets/images/Nicole_Bra_FrontZOOM2.jpg",
      "/assets/images/Nicole_Bra_Thong_Front.jpg",
      "/assets/images/Nicole_Bra_ThongChains_Back.jpg",
      "/assets/images/Nicole_Bra_ThongChains_Side.jpg",
      "/assets/images/Nicole.jpg",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Thong_Front_d.jpg",
      name: "Sianie",
      height: '5\' 9\'\' / 175 CM',
      bust: '33.5" / 10D',
      waist: '26" / 66cm',
      hips: '36.5" / 93cm',
      dress: 6,
    }
  },
  {
    id: 69,
    type: 'lucinda-panty',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Lucinda Panty',
    favorite: false,
    price: 120.00,
    image: '/assets/images/Lucinda_Bra_BriefRuffle_Back2.webp',
    onSale: false,
    color: 'white',
    thumbnail: [
      "/assets/images/Lucinda_Bra_BriefRuffle_Back2.webp",
      "/assets/images/Lucinda_BriefRuffle_Front2.webp",
      "/assets/images/Lucinda_Brief_Front1.webp",
      "/assets/images/Lucinda_BriefRuffle_Back.webp",
      "/assets/images/Lucinda_Brief_Back.webp",
      "/assets/images/Lucinda_BriefRuffle_Side.jpg",
      "/assets/images/Lucinda_Brief_Side.jpg",
      "/assets/images/Lucinda_Bra_BriefRuffle_Front1.jpg",
      "/assets/images/Lucinda_Bra_Brief_Front1.jpg",
      "/assets/images/Lucinda_Bra_BriefRuffle_Back.jpg",
      "/assets/images/Lucinda_Bra_Brief_Back.jpg",
      "/assets/images/Lucinda_Bra_BriefRuffle_Side.jpg",
      "/assets/images/Lucinda_Bra_Brief_Side.jpg",
      "/assets/images/Lucinda.jpg",
    ],
    model: {
      photo: "/assets/images/Taisha_Bra_Brief_Bullet_Front_2.jpg",
      name: "Taisha",
      height: '5\' 9\'\' / 176 CM',
      bust: '35.5" / 10D',
      waist: '29" / 74cm',
      hips: '39.5" / 100cm',
      dress: 8,
    }
  },
  {
    id: 70,
    type: 'esme-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Esme Bra',
    favorite: false,
    price: 120.00,
    image: '/assets/images/Esme_Bra_Thong_Front.webp',
    onSale: false,
    color: 'black',
    thumbnail: [
      "/assets/images/Esme_Bra_Thong_Front.webp",
      "/assets/images/Esme_Bra_Front5.webp",
      "/assets/images/Esme_Bra_Back1.webp",
      "/assets/images/Esme_Bra_Side2.webp",
      "/assets/images/Esme_Bra_FrontZOOM3.webp",
      "/assets/images/Esme_Bra_Thong_Front1.webp",
      "/assets/images/Esme_Bra_Thong_Back.webp",
      "/assets/images/Esme_Bra_Thong_Side.webp",
      "/assets/images/Campaign_Esme.webp",
    ],
    model: {
      photo: "/assets/images/Taisha_Bra_Brief_Bullet_Front_2.jpg",
      name: "Taisha",
      height: '5\' 9\'\' / 176 CM',
      bust: '35.5" / 10D',
      waist: '29" / 74cm',
      hips: '39.5" / 100cm',
      dress: 8,
    }
  },
  {
    id: 71,
    type: 'tallulah-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Tallulah Bra',
    favorite: false,
    price: 110.00,
    image: '/assets/images/Tallulah_Bra_Thong_Front1.webp',
    onSale: false,
    color: 'hot pink',
    thumbnail: [
      "/assets/images/Tallulah_Bra_Thong_Front1.webp",
      "/assets/images/Tallulah_BraZOOM.jpg",
      "/assets/images/Tallulah_Bra_Front4.webp",
      "/assets/images/Tallulah_Bra_Back1.webp",
      "/assets/images/Tallulah_Bra_Side1.webp",
      "/assets/images/Tallulah_Bra_FrontZOOM6.webp",
      "/assets/images/Tallulah_Bra_Thong_Front.webp",
      "/assets/images/Tallulah_Bra_Thong_Back.webp",
      "/assets/images/Tallulah_Bra_Thong_Side.webp",
      "/assets/images/Shot_14_4452-Editar.webp",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Brief_Front.jpg",
      name: "Larni",
      height: '5\' 9\'\' / 175 CM',
      bust: '34.5" / 10D',
      waist: '26.5" / 67.5cm',
      hips: '37" / 93.5cm',
      dress: 8,
    }
  },
  {
    id: 72,
    type: 'blossom-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Blossom Bra',
    favorite: false,
    price: 125.00,
    image: '/assets/images/Blossom_Bra_Thong_Front.webp',
    onSale: false,
    color: 'yellow',
    thumbnail: [
      "/assets/images/Blossom_Bra_Thong_Front.webp",
      "/assets/images/Blossom_BraZOOM.webp",
      "/assets/images/Blossom_Bra_Front1.webp",
      "/assets/images/Blossom_Bra_Back.webp",
      "/assets/images/Blossom_Bra_Side2.webp",
      "/assets/images/Blossom_Bra_FrontZOOM1.webp",
      "/assets/images/Blossom_Bra_Thong_Side1.webp",
      "/assets/images/Blossom_Bra_Thong_Back.webp",
      "/assets/images/Blossom_Bra_Thong_Side.webp",
      "/assets/images/21_14790_FLAT.webp",
    ],
    model: {
      photo: "/assets/images/Eleanor_Bra_Brief_Front.jpg",
      name: "Renee",
      height: '5\' 4\'\' / 162 CM',
      bust: '34" / 10C',
      waist: '23" / 58.5cm',
      hips: '35" / 89cm',
      dress: 6,
    }
  },
  {
    id: 73,
    type: 'addison-leopard-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Addison Bra',
    favorite: false,
    price: 150.00,
    image: '/assets/images/Addison_Bra_Brief_Front.webp',
    onSale: false,
    color: 'leopard',
    thumbnail: [
      "/assets/images/Addison_Bra_Brief_Front.webp",
      "/assets/images/Addison_Bra_Front.webp",
      "/assets/images/Addison_Bra_Back.webp",
      "/assets/images/Addison_Bra_Side1.webp",
      "/assets/images/Addison_BraZOOM.webp",
      "/assets/images/Addison_BraZOOM1.webp",
      "/assets/images/Addison_Bra_Brief_Bullet_Front.webp",
      "/assets/images/Addison_Bra_Brief_Back.webp",
      "/assets/images/Addison_Bra_Brief_Side.webp",
      "/assets/images/Addison_1.webp",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Thong_Front_d.jpg",
      name: "Sianie",
      height: '5\' 4\'\' / 162 CM',
      bust: '30" / 10D',
      waist: '22" / 56.5cm',
      hips: '35.5" / 90cm',
      dress: 6,
    }
  },
  {
    id: 74,
    type: 'nakeds-almond-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Nakeds Bra',
    favorite: false,
    price: 125.00,
    image: '/assets/images/NAlmond_Bra_Brief_Front2.webp',
    onSale: false,
    color: 'almond',
    thumbnail: [
      "/assets/images/NAlmond_Bra_Brief_Front2.webp",
      "/assets/images/NAlmond_Bra_Front8.webp",
      "/assets/images/NAlmond_Bra_Brief_Back1_2.webp",
      "/assets/images/NAlmond_Bra_Brief_Side1.webp",
      "/assets/images/NAlmond_Bra_Thong_Front.webp",
      "/assets/images/NAlmond_Bra_Thong_Back.webp",
      "/assets/images/NAlmond_Bra_SideZOOM4.webp",
      "/assets/images/NAlmond_Bra_Back4.webp",
      "/assets/images/NAlmond_Bra_Front7.webp",
      "/assets/images/NAlmond_Bra_Back3.webp",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Thong_Front_d.jpg",
      name: "Sianie",
      height: '5\' 4\'\' / 162 CM',
      bust: '30" / 10D',
      waist: '22" / 56.5cm',
      hips: '35.5" / 90cm',
      dress: 6,
    }
  },
  {
    id: 75,
    type: 'thandie-suspender',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Thandie Suspender',
    favorite: false,
    price: 125.00,
    image: '/assets/images/Thandie_Bra_Suspender_Thong_Front.jpg',
    onSale: false,
    color: 'black',
    thumbnail: [
      "/assets/images/Thandie_Bra_Suspender_Thong_Front.jpg",
      "/assets/images/Thandie_Thong_Suspender_Front1.jpg",
      "/assets/images/Thandie_Thong_Suspender_Back.jpg",
      "/assets/images/Thandie_Thong_Suspender_Side.webp",
      "/assets/images/Thandie_Bra_Suspender_Thong_Front1.webp",
      "/assets/images/Thandie_Bra_Suspender_Thong_Back_5.webp",
      "/assets/images/Thandie_Bra_Suspender_Thong_Side.webp",
      "/assets/images/Campaign_Imagery_Thandie.webp",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Thong_Front_d.jpg",
      name: "Sianie",
      height: '5\' 4\'\' / 162 CM',
      bust: '30" / 10D',
      waist: '22" / 56.5cm',
      hips: '35.5" / 90cm',
      dress: 6,
    }
  },
  {
    id: 76,
    type: 'kukuro-red-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Kukuro Red Bra',
    favorite: false,
    price: 160.00,
    image: '/assets/images/Kukuro_Bra_Front1_1.jpg',
    onSale: false,
    color: 'purple',
    thumbnail: [
      "/assets/images/Kukuro_Bra_Front1_1.jpg",
      "/assets/images/Kukuro_Bra_Back1.jpg",
      "/assets/images/Kukuro_Bra_Side_1.jpg",
      "/assets/images/Kukuro_Bra_FrontZOOM2.jpg",
      "/assets/images/KukuroRed2.jpg",
      "/assets/images/Kukuro_Bra_Brief_Front1_1.jpg",
      "/assets/images/Kukuro_Bra_Brief_Back1.jpg",
      "/assets/images/Kukuro_Bra_Brief_Side_2.jpg",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Thong_Front_d.jpg",
      name: "Sianie",
      height: '5\' 4\'\' / 162 CM',
      bust: '30" / 10D',
      waist: '22" / 56.5cm',
      hips: '35.5" / 90cm',
      dress: 6,
    }
  },
  {
    id: 77,
    type: 'kukuro-purple-suspender',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Kukuro Suspender',
    favorite: false,
    price: 140.00,
    image: '/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Front.webp',
    onSale: false,
    color: 'purple',
    thumbnail: [
      "/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Front.webp",
      "/assets/images/Kukuro_SuspenderGartersStockings_Thong_Front1.webp",
      "/assets/images/Kukuro_SuspenderGartersStockings_Thong_Back1.webp",
      "/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Sidewebp.webp",
      "/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Front1.webp",
      "/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Back.webp",
      "/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Back1.webp",
      "/assets/images/Kukuro_Bra_SuspenderGarters_Thong_Front.webp",
      "/assets/images/Kukuro_Bra_SuspenderGarters_Thong_Back.webp",
      "/assets/images/Kukuro_Bra_SuspenderGarters_Brief_Cuffs_Back.webp",
      "/assets/images/Kukuro_SuspenderGarters_Thong_Front.webp",
      "/assets/images/Kukuro_SuspenderGarters_Thong_Side.webp",
      "/assets/images/Kukuro_SuspenderGarters_Thong_Back.webp",
      "/assets/images/Kukuro_SuspenderStockings_Thong_Front.webp",
      "/assets/images/Kukuro_SuspenderStockings_Thong_Side.webp",
      "/assets/images/Kukuro_SuspenderStockings_Thong_Back.webp",
    ],
    model: {
      photo: "/assets/images/Kukuro_Bra_Thong_Front_d.jpg",
      name: "Sianie",
      height: '5\' 4\'\' / 162 CM',
      bust: '30" / 10D',
      waist: '22" / 56.5cm',
      hips: '35.5" / 90cm',
      dress: 6,
    }
  },
  {
    id: 78,
    type: 'kukuro-purple-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Kukuro Purple Bra',
    favorite: false,
    price: 160.00,
    image: '/assets/images/Kukuro_Bra_Thong_Front.webp',
    onSale: false,
    color: 'purple',
    thumbnail: [
      "/assets/images/Kukuro_Bra_Thong_Front.webp",
      "/assets/images/Kukuro_Bra_Front.webp",
      "/assets/images/Kukuro_Bra_Thong_Side.webp",
      "/assets/images/Kukuro_Bra_Thong_Back.webp",
      "/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Front1.webp",
      "/assets/images/Kukuro_Bra_SuspenderGartersStockings_Thong_Back.webp",
      "/assets/images/Kukuro_Bra_Side2.webp",
      "/assets/images/Kukuro_Bra_SideZOOM2.webp",
      "/assets/images/Kukuro_Bra_FrontZOOM5.webp",
      "/assets/images/Kukuro_Bra_Back2.webp",
      "/assets/images/Kukuro_Bra_Brief_Front.webp",
      "/assets/images/Kukuro_Bra_Brief_Back.webp",
      "/assets/images/Kukuro_Bra_Front2.webp",
      "/assets/images/Kukuro_Bra_Back_1.webp",
    ],
    model: {
      photo: "/assets/images/NNero_Bra_Brief_Front2.jpg",
      name: "crystal",
      height: '5\' 4\'\' / 162 CM',
      bust: '30" / 10D',
      waist: '22" / 56.5cm',
      hips: '35.5" / 90cm',
      dress: 6,
    }
  },
  {
    id: 79,
    type: 'lingerie-white',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Snow Queen',
    favorite: true,
    price: 50.00,
    originalPrice: 65.00,
    image: '/assets/images/sensual-woman-beautiful-young-woman-in-lingerie-smiling-while-standing.jpg',
    onSale: true,
    color: 'white',
    thumbnail: [
      "/assets/images/sensual-woman-beautiful-young-woman-in-lingerie.jpg",
      "/assets/images/sensual-beauty-beautiful-young-woman-in-lingerie-2.jpg",
      "/assets/images/pure-beauty.jpg",
      "/assets/images/flirty-beauty-attractive-young-woman-in-lingerie.jpg"
    ],
    model: {
      photo: "/assets/images/pure-beauty.jpg",
      name: "keesha",
      height: '5\'9" / 176cm',
      bust: '35.5" / 10D',
      waist: '29" / 74cm',
      hips: '39.5" / 100cm',
      dress: 8,
    }
  },
  {
    id: 85,
    type: 'heart-beat',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Heart Beat',
    favorite: true,
    price: 75.00,
    image: '/assets/images/sexy-young-lady-in-luxury-lingerie.jpg',
    onSale: false
  },
  {
    id: 90,
    type: 'victoria-line',
    category: {
      name: 'underwear',
      tag: 'underwear',
    },
    name: 'Victoria Line',
    favorite: true,
    price: 70.00,
    image: '/assets/images/beautiful-seductive-girl-posing-in-black-lingerie.jpg',
    onSale: false
  },
  {
    id: 92,
    type: 'slick-bodysuit',
    category: {
      name: 'bodysuit',
      tag: 'bodysuit',
    },
    name: 'Slick Bodysuit',
    favorite: false,
    price: 68.00,
    image: '/assets/images/beauty-in-lingerie.jpg',
    onSale: false
  },
  {
    id: 93,
    type: 'cloud-fit',
    category: {
      name: 'underwear',
      tag: 'underwear',
    },
    name: 'Cloud Fit',
    favorite: true,
    price: 65.00,
    image: '/assets/images/posing-for-a-camera-beautiful-woman-with-slim-body-in-underwear-is-in-the-studio.jpg',
    onSale: false
  },
  {
    id: 94,
    type: 'black-swan',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Black Swan',
    favorite: true,
    price: 75.00,
    image: '/assets/images/blonde-tender-girl-posing-in-black-lingerie.jpg',
    onSale: false
  },
  {
    id: 95,
    type: 'gray-shade',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Gray Shade',
    favorite: true,
    price: 75.00,
    image: '/assets/images/beautiful-sensual-girl-posing-in-lace-lingerie-isolated-on-grey.jpg',
    onSale: false
  },
  {
    id: 96,
    type: 'pink-love',
    category: {
      name: 'underwear',
      tag: 'underwear',
    },
    name: 'Pink Love',
    favorite: true,
    price: 68.00,
    image: '/assets/images/woman-with-beautiful-body.jpg',
    onSale: false
  },
  {
    id: 97,
    type: 'strapless-multiway-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Strapless bra',
    favorite: true,
    price: 37.00,
    originalPrice: 46.00,
    image: '/assets/images/Strapless-Microfibre-Multiway-Bra.jpg',
    onSale: false
  },
  {
    id: 98,
    type: 'strapless-u-wire-bra',
    category: {
      name: 'lingerie',
      tag: 'lingerie',
    },
    name: 'Strapless u-wire bra',
    favorite: false,
    price: 10.00,
    originalPrice: 12.00,
    image: '/assets/images/Strapless-u-wire-microfibre-multiway-bra.jpg',
    onSale: false
  },
  {
    id: 99,
    type: 'bodysuit-honeymoon',
    category: {
      name: 'bodysuit',
      tag: 'bodysuit',
    },
    name: 'Bodysuit Honeymoon',
    favorite: false,
    price: 34.00,
    image: '/assets/images/bodysuit.jpg',
    onSale: true
  },
  {
    id: 100,
    type: 'bridal-bodysuit',
    category: {
      name: 'bodysuit',
      tag: 'bodysuit',
    },
    name: 'Bridal Bodysuit White Lace',
    favorite: false,
    price: 34.00,
    image: '/assets/images/bridal_lingerie_bodysuit_white_lace.jpg',
    onSale: true
  },
]
